python unit_test_prepare_input.py 		\
	--env Pinch 		\
	--stage dy 		\
	--eval_epoch 85		\
	--eval_iter 110000	\
	--eval_set demo 	\
	--verbose_data 0	\
	--sequence_length 36	\
	--n_his 35		\
	--augment 0.05		\
	--vispy 1
